version: '3.8'

services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skroutz
    image: postgres:15.2
    ports:
      - 5432:5432
    expose:
      - 5432
